In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def getpd(df, trace):
    return df[trace][df[trace].columns[0]].to_numpy()

path='C:/Users/Zucchi/Documents/Medidas/CH6/2P-231116 150535.csv'

df=pd.read_csv(path, header=[0, 1])

V=getpd(df, "V2")
I=getpd(df, "I2")

In [2]:
I

array([-1.000e-03, -9.798e-04, -9.596e-04, -9.394e-04, -9.192e-04,
       -8.990e-04, -8.788e-04, -8.586e-04, -8.384e-04, -8.182e-04,
       -7.980e-04, -7.778e-04, -7.576e-04, -7.374e-04, -7.172e-04,
       -6.970e-04, -6.768e-04, -6.566e-04, -6.364e-04, -6.162e-04,
       -5.960e-04, -5.758e-04, -5.556e-04, -5.354e-04, -5.152e-04,
       -4.950e-04, -4.748e-04, -4.546e-04, -4.344e-04, -4.142e-04,
       -3.940e-04, -3.738e-04, -3.536e-04, -3.334e-04, -3.132e-04,
       -2.930e-04, -2.728e-04, -2.526e-04, -2.324e-04, -2.122e-04,
       -1.920e-04, -1.718e-04, -1.516e-04, -1.314e-04, -1.112e-04,
       -9.100e-05, -7.080e-05, -5.060e-05, -3.040e-05, -1.020e-05,
        1.000e-05,  3.020e-05,  5.040e-05,  7.060e-05,  9.080e-05,
        1.110e-04,  1.312e-04,  1.514e-04,  1.716e-04,  1.918e-04,
        2.120e-04,  2.322e-04,  2.524e-04,  2.726e-04,  2.928e-04,
        3.130e-04,  3.332e-04,  3.534e-04,  3.736e-04,  3.938e-04,
        4.140e-04,  4.342e-04,  4.544e-04,  4.746e-04,  4.948e

In [3]:
V

array([-0.02802 , -0.027448, -0.02688 , -0.026316, -0.025748, -0.02518 ,
       -0.024616, -0.024048, -0.023476, -0.022914, -0.022344, -0.021776,
       -0.021212, -0.020642, -0.020076, -0.01951 , -0.018944, -0.018372,
       -0.017808, -0.017238, -0.016672, -0.016102, -0.015532, -0.014968,
       -0.014404, -0.013836, -0.013268, -0.012704, -0.012142, -0.011572,
       -0.01101 , -0.01044 , -0.009878, -0.009314, -0.008744, -0.00818 ,
       -0.007614, -0.007046, -0.006484, -0.00592 , -0.005352, -0.004788,
       -0.004222, -0.003658, -0.003092, -0.002588, -0.002006, -0.00143 ,
       -0.000852, -0.000276,  0.0003  ,  0.000878,  0.001456,  0.002054,
        0.002652,  0.00325 ,  0.003678,  0.004246,  0.004812,  0.005374,
        0.005938,  0.006506,  0.00707 ,  0.007632,  0.0082  ,  0.00876 ,
        0.009332,  0.0099  ,  0.010464,  0.011028,  0.011592,  0.012156,
        0.012724,  0.01329 ,  0.013856,  0.014426,  0.01499 ,  0.015558,
        0.01613 ,  0.016692,  0.017264,  0.017828, 

In [6]:
np.polyfit(I, V, 1)

array([2.80109336e+01, 1.52610934e-05])